
export const CommonAction = {
  LOAD_REAL_TIME_SEARCH_DATA: 'LOAD_REAL_TIME_SEARCH_DATA',
  LOAD_INDIVIDUAL_SEARCH_DATA: 'LOAD_INDIVIDUAL_SEARCH_DATA',
  LOAD_REAL_TIME_USER_DATA: 'LOAD_REAL_TIME_USER_DATA',
  LOAD_USER_LOCATION_MAP_DATA: 'LOAD_USER_LOCATION_MAP_DATA',
};

export const MainPageAction = {
  LOAD_STATS: 'LOAD_STATS',
  LOAD_KEYWORD_SEARCH_RANKINGS: 'LOAD_KEYWORD_SEARCH_RANKINGS',
  LOAD_DATA_BROWSE_RANKINGS: 'LOAD_DATA_BROWSE_RANKINGS',
  LOAD_SEARCH_USER_RANKINGS: 'LOAD_SEARCH_USER_RANKINGS'
};

export const KeywordPageAction = {
  LOAD_STATS: 'LOAD_STATS',
  LOAD_SEARCHED_KEYWORD_RANKINGS: 'LOAD_SEARCHED_KEYWORD_RANKINGS',
  LOAD_KEYWORD_SEARCH_TREND: 'LOAD_KEYWORD_SEARCH_TREND',
  LOAD_SEARCH_CONVERSION: 'LOAD_SEARCH_CONVERSION',
  LOAD_MISSED_KEYWORD_RANKING: 'LOAD_MISSED_KEYWORD_RANKING'
};

export const DataPageAction = {
  LOAD_STATS: 'LOAD_STATS',
  LOAD_DATA_USAGE_RECORD: 'LOAD_DATA_USAGE_RECORD',
  LOAD_DATA_USAGE_RATIO: 'LOAD_DATA_USAGE_RATIO',
  LOAD_DATA_SEARCH_RATIO: 'LOAD_DATA_SEARCH_RATIO',
  LOAD_DATA_USAGE_TREND: 'LOAD_DATA_USAGE_TREND',
  LOAD_DATA_USAGE_RANKINGS: 'LOAD_DATA_USAGE_RANKINGS'
};

export const UserAction = {
  LOAD_SEARCH_TREND: 'LOAD_SEARCH_TREND',
  LOAD_LOCATION_MAP_DATA: 'LOAD_LOCATION_MAP_DATA',
  LOAD_SEARCH_USER_RANKINGS: 'LOAD_SEARCH_USER_RANKINGS',
  LOAD_BROWSE_USER_RANKINGS: 'LOAD_BROWSE_USER_RANKINGS'
};


export const SearchAction = {
  SEARCH: 'SEARCH',
  LOAD_SEARCH_RESULTS: 'LOAD_SEARCH_RESULTS'
};
