
export const CommonAction = {
  //charts
  LOAD_REAL_TIME_SEARCH_DATA: 'LOAD_REAL_TIME_SEARCH_DATA',
  LOAD_INDIVIDUAL_SEARCH_DATA: 'LOAD_INDIVIDUAL_SEARCH_DATA',
  LOAD_REAL_TIME_USER_DATA: 'LOAD_REAL_TIME_USER_DATA',
  LOAD_USER_LOCATION_MAP_DATA: 'LOAD_USER_LOCATION_MAP_DATA',
  LOAD_KEYWORD_SEARCH_TREND: 'LOAD_KEYWORD_SEARCH_TREND',
  LOAD_KEYWORD_SEARCH_CONVERSION: 'LOAD_SEARCH_CONVERSION',
  LOAD_USER_SEARCH_TREND: 'LOAD_USER_SEARCH_TREND',
  LOAD_LOCATION_MAP_DATA: 'LOAD_LOCATION_MAP_DATA',
  LOAD_DATA_USAGE_RATIO: 'LOAD_DATA_USAGE_RATIO',
  LOAD_DATA_SEARCH_RATIO: 'LOAD_DATA_SEARCH_RATIO',
  LOAD_DATA_USAGE_TREND: 'LOAD_DATA_USAGE_TREND',

  //rankings
  LOAD_SEARCHED_KEYWORD_RANKINGS: 'LOAD_SEARCHED_KEYWORD_RANKINGS',
  LOAD_DATA_BROWSE_RANKINGS: 'LOAD_DATA_BROWSE_RANKINGS',
  LOAD_SEARCH_USER_RANKINGS: 'LOAD_SEARCH_USER_RANKINGS',
  LOAD_MISSED_KEYWORD_RANKING: 'LOAD_MISSED_KEYWORD_RANKING',
  LOAD_BROWSE_USER_RANKINGS: 'LOAD_BROWSE_USER_RANKINGS',
  LOAD_DATA_USAGE_RANKINGS: 'LOAD_DATA_USAGE_RANKINGS',
  LOAD_CATEGORIZED_RANKINGS: 'LOAD_CATEGORIZED_RANKINGS',
  LOAD_RELATED_DATA_RANKINGS: 'LOAD_RELATED_DATA_RANKINGS',
  LOAD_RECENT_SEARCH_USER_RANKINGS: 'LOAD_RECENT_SEARCH_USER_RANKINGS',

  FETCH_IN_PROGRESS: 'FETCH_IN_PROGRESS'
};

export const StatsAction = {
  LOAD_TOTAL_DATA: 'LOAD_TOTAL_DATA',
  LOAD_TOTAL_SEARCH: 'LOAD_TOTAL_SEARCH',
  LOAD_INDIVIDUAL_SEARCH: 'LOAD_INDIVIDUAL_SEARCH',
  LOAD_INDIVIDUAL_USER: 'LOAD_INDIVIDUAL_USER',
  LOAD_TODAY_SEARCH: 'LOAD_TODAY_SEARCH',
  LOAD_AVERAGE_SEARCH: 'LOAD_AVERAGE_SEARCH',
  LOAD_TODAY_BROWSED: 'LOAD_TODAY_BROWSED',
  LOAD_INDIVIDUALLY_BROWSED: 'LOAD_INDIVIDUALLY_BROWSED',
};

export const DataAction = {
  LOAD_DATA_USAGE_RECORD: 'LOAD_DATA_USAGE_RECORD'
};

export const UserAction = {

};


export const SearchAction = {
  LOAD_SEARCH_KEYWORD: 'LOAD_SEARCH_KEYWORD',
  LOAD_SEARCH_RESULT: 'LOAD_SEARCH_RESULT'
};
